import 'dart:convert';

import 'package:covid_app/model/counteryslist.dart';
import 'package:covid_app/model/datamodel.dart';
import 'package:covid_app/services/appurl.dart';
import 'package:http/http.dart'as http;
class CounterState{
  Future <Autogenerated> covidstates()async{
    final response = await http.get(Uri.parse(apiurl.worldsstateapi));
  
    var data = jsonDecode(response.body);
   
    if(response.statusCode ==200)
    {

      return Autogenerated.fromJson(data);
    }
    else{
      throw Exception("error");
    }

  }
    Future<List <dynamic>> counteryData()async{
    final response = await http.get(Uri.parse(apiurl.contrylist));
  
    var data = jsonDecode(response.body);
    if(response.statusCode ==200)
    {
      return data;
    }
    else{
      throw Exception("error");
    }

  }
}

