import 'package:covid_app/model/datamodel.dart';
import 'package:retrofit/retrofit.dart';
import 'package:dio/dio.dart';

part 'retrofit.g.dart';

@RestApi(baseUrl: "https://disease.sh/v3/covid-19") 
abstract class ApiService {
  factory ApiService(Dio dio, {String baseUrl}) = _ApiService;

  @GET("/all")
  Future<Autogenerated> getCovidStates();
}

